### ISSUE TITLE
Lava Bucket does not become usable after leaving area where it is banned.

### ISSUE THREAD

**Issue by ArtiOJ** [RTClarkV/MapProtect#40]
Title. Create a new area with the lava bucket unusable. You can not place it when you are in the area, but you do not regain the ability to place it after you leave. Things like water buckets and ender pearls have not been tested.

https://github.com/RTClarkV/MapProtect/assets/68037726/394df0bc-0454-4e32-a15f-34dd71d0f1cf

**Comment by RTClarkV** [comment]
Nice, my unusable item's handler doesn't check for any locations, explaining this bug. It will be fixed this week.

**Comment by RTClarkV** [comment]
fixed.
