### ISSUE TITLE
Hard to tell when MP is done reloading

### ISSUE THREAD

**Issue by ArtiOJ** [RTClarkV/MapProtect#43]
As the title says, I have trouble seeing when MP is done reloading, I would suggest having it say "MapProtect reloaded." or something when it is done.

**Comment by RTClarkV** [comment]
good point, it just says "reloading." I'll let the user know when the loop is closed.

**Comment by RTClarkV** [comment]
<img width="601" alt="image" src="https://github.com/RTClarkV/MapProtect/assets/155603248/d1110f38-67e1-401e-82d7-93511535c0da">

Made /mpreload more user friendly. Will be released next update.
