### ISSUE TITLE
Region is one block smaller than selected area

### ISSUE THREAD

**Issue by ArtiOJ** [RTClarkV/MapProtect#44]
https://github.com/RTClarkV/MapProtect/assets/68037726/986432f0-abf1-46df-b37e-81b97f02decd

Not sure why this happens, it should be an easy fix, though.

**Comment by RTClarkV** [comment]
oh this thing. I noticed this in development and felt like it happened sometimes in a certain cardinal direction. Could you figure out what direction and if it always happens please?

**Comment by RTClarkV** [comment]
Patched for next update, 1.2
