### ISSUE TITLE
Softlock when region can not "pull" you back in

### ISSUE THREAD

**Issue by ArtiOJ** [RTClarkV/MapProtect#47]
https://github.com/RTClarkV/MapProtect/assets/68037726/12efcce5-1059-4cfb-a61e-32b82e25a026

If players are not allowed to exit the region but can not get pulled in when they try to leave, they are soft-locked. Probably implement a solution similar to #45

**Comment by RTClarkV** [comment]
hmmmmmm. It should teleport you back in after a certain amount of failed attempts to "pull" you in. Was it not doing that?

**Comment by RTClarkV** [comment]
on a second look it is teleporting you, but the blocks are pushing you back out. This seems like an issue that only occurs under very specific circumstances. Can you post a video on how you created this phenomenon?

**Comment by RTClarkV** [comment]
I replicated the issue. They can't get out and will end up dying from suffocation, fixing the issue when they respawn.
