### ISSUE TITLE
Setting build to false is not doing anything

### ISSUE THREAD

**Issue by ArtiOJ** [RTClarkV/MapProtect#50]
I tried setting the build to false, but it did not do anything.

**Comment by RTClarkV** [comment]
uhhh check to make sure you're not OPed.

**Comment by RTClarkV** [comment]
okay, build should be fine, check your config settings. if build is false, the placeable / unplaceable lists are now in effect. If you set the lists to **_inverse_**, that might be the problem. Please send a screenshot of your config. I'll make sure it's not broken later today.

**Comment by RTClarkV** [comment]
I retested the build. It works just fine. If the player has OP or the permission mp.admin, setting build to false will not do anything. This feature is intended.
